name: Build-Release

on:
  push:
    branches: [ main ]


jobs:
  platformio-build:
    runs-on: ubuntu-latest
    container: fishros2/ros2pio:humble

    steps:
      - uses: actions/checkout@v2

      - name: Build firmware
        run: /bin/bash release.sh
